@startuml


class Client
interface Star

RealStar<..ProxyStar
ProxyStar<..Client
Star<|-ProxyStar
Star<|- RealStar


class ProxyStar{
confer();..
}
class RealStar{
confer();..
}

@enduml